### ISSUE TITLE
A little HOWTO would make this super useful

### ISSUE THREAD

**Issue by dabrahams** [robn/sasl2-oauth#1]
Once I get it installed, I’d love to know how to configure postfix to use it!

Thanks,
Dave

**Comment by robn** [comment]
It's hard to provide a general documentation because this is just the client library - configuring it is entirely dependent on the software using it.

For Postfix, follow the [Postfix SASL Howto](http://www.postfix.org/SASL_README.html#client_sasl). It's exactly the same as configuring for PLAIN (so you'll need `noplaintext`), with the bearer token in `password` field in your password map. The only trick is that you need to force it to use the XOAUTH2 mechanism, otherwise it will try to use PLAIN:

```
smtp_sasl_mechanism_filter = XOAUTH2
```

The other thing to know is that on most services (Gmail), the bearer token is short-lived, and needs to be regnerated regularly from the refresh token. At FastMail we use Postfix's `socketmap` table to connect to a daemon process which gets the refresh token from the database, does a request to the remote service to get a bearer token and then return that Postfix. For small numbers of users, it might be sufficient to run a cron job the refreshes tokens and rebuilds the password map.

**Comment by dabrahams** [comment]
Thanks!

I didn’t know about these tokens (really I know nothing about OAUTH2 yet; I’m just trying to avoid [enabling less-secure applications](https://support.google.com/accounts/answer/6010255?hl=en), and it sounds a bit complex.  I’m just using postfix as to queue and relay outgoing email from my personal machine.  Can you suggest an approach for this case?

**Comment by robn** [comment]
If it were me I'd use the cronjob method - every X (half-hour maybe), get a new bearer token and recreate the password map.

The "get a new bearer token" bit would require some command line program that can speak OAuth2. I'm not familiar with any, but I'd put good money on one or two existing. You could also fake it with curl. Google have a bunch of docs showing how to make the calls.
